### ISSUE TITLE
Cool!  Is there a compiled version of the driver?

### ISSUE THREAD

**Issue by sidwray** [jkew/airtable.java#1]
At Tableau we using Airtable to manage some of our internal Connectivity information.  Do you have a compiled version of the JDBC driver i could test?  

Also, we now have the packaging and signing feature ready to bundle your connector as a ".taco" connector file that works natively with Tableau 2019.4.  https://tableau.github.io/connector-plugin-sdk/docs/package-sign . Check it out!!

-Sid

**Comment by jkew** [comment]
https://github.com/jkew/airtable.java/releases/tag/0.2.2-JDBC
